### PR TITLE
Display City in 'Afficher toutes les seances'

### PR DESCRIPTION
**Pull request by cdancette**
Hi Neamar,
This is a new PR for cities display:

It displays the city in the "Afficher toutes les séances" view.

photo_2019-02-01_14-09-56

### CODE REVIEW

**Comment by Neamar** [comment]
Salut !

I assume you had multiple cinemas named the same way?

I'm afraid of the impact this could have on "standard" users that probably only have one city, and will now see more noise on their screen.

What do you think? Is there a way to mitigate this while still fixing the problem you're experiencing?

**Comment by cdancette** [comment]
I don't have cinemas named the same way, but I have 8 cinemas registered, so I don't remember in which city they are, based only on the name. That's why I find it convenient to have the city displayed.

For people who have only 1 cinema, I think they wouldn't use the "Afficher toutes les séances" view, but would click directly on the cinema (where the city won't be displayed). Here, it adds only the city name, but the cinema name was already displayed.

What do you think ?

**Comment by Neamar** [comment]
I'm more thinking about users who have multiple cinemas in one city -- that's my case for instance. I only go to cinemas in my home town, so all cinemas would display "Lyon".

**Comment by cdancette** [comment]
You're right, it can add some noise, i'm not sure how to deal with this. 

I was thinking we could "group" by city, but I checked in Paris and Lyon for example, they are registered with "arrondissement", so we can't really do this either.

**Comment by Neamar** [comment]
Closing in favor of major rewrite in #88

**Pull request closed without merging**
